//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterFootball
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalCenterEntities : DbContext
    {
        private static MedicalCenterEntities _context;
        public MedicalCenterEntities()
            : base("name=MedicalCenterEntities")
        {
        }
        public static MedicalCenterEntities GetContext()
        {
            if (_context == null)
                _context = new MedicalCenterEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MassageTherapistReports> MassageTherapistReports { get; set; }
        public virtual DbSet<PhysiotherapistReports> PhysiotherapistReports { get; set; }
        public virtual DbSet<RehabTherapistReports> RehabTherapistReports { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
