//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterFootball
{
    using System;
    using System.Collections.Generic;
    
    public partial class RehabTherapistReports
    {
        public int ReportID { get; set; }
        public string PlayerName { get; set; }
        public string ExerciseType { get; set; }
        public Nullable<int> Repetitions { get; set; }
        public string Remarks { get; set; }
    }
}
